import { FieldCard, inputClass } from './shared';

type Props = { value: Record<string, unknown>; onChange: (k: string, v: unknown) => void; onSubmit: () => void; loading: boolean; title: string; fields: Array<{ key: string; label: string; options?: string[]; type?: 'number' }>; };

function Generic({ value, onChange, onSubmit, loading, title, fields }: Props) {
  return <form onSubmit={(e)=>{e.preventDefault(); onSubmit();}} className='mt-6 grid gap-4'>
    <FieldCard title={title} icon='📊'>{fields.map((f)=>f.options ? <select key={f.key} className={inputClass} value={(value[f.key] as string) ?? ''} onChange={(e)=>onChange(f.key, e.target.value)}><option value=''>{f.label}</option>{f.options.map((o)=><option key={o} value={o}>{o}</option>)}</select> : <input key={f.key} type={f.type === 'number' ? 'number' : 'text'} className={inputClass} placeholder={f.label} value={(value[f.key] as string | number) ?? ''} onChange={(e)=>onChange(f.key, f.type === 'number' ? Number(e.target.value) : e.target.value)} />)}</FieldCard>
    <button disabled={loading} className='h-11 rounded-xl bg-amber-400 px-4 font-semibold text-slate-900'>{loading?'Guardando...':'Guardar ficha técnica'}</button>
  </form>;
}

export const CasaForm = (p: Omit<Props, 'title'|'fields'>) => <Generic {...p} title='Ficha técnica residencial · Casa' fields={[
  { key:'ciudad', label:'Ciudad' },{ key:'zona', label:'Zona' },{ key:'areaTerreno', label:'Área terreno', type:'number' },{ key:'areaConstruccion', label:'Área construcción', type:'number' },{ key:'niveles', label:'Niveles', type:'number' },{ key:'habitaciones', label:'Habitaciones', type:'number' },{ key:'banos', label:'Baños', type:'number' },{ key:'garaje', label:'Garaje', type:'number' },{ key:'tipoConstruccion', label:'Tipo construcción', options:['Lujo moderno','Residencial alta','Residencial media','Económica'] },{ key:'estadoConstruccion', label:'Estado construcción', options:['Excelente','Bueno','Regular','Malo'] },{ key:'antiguedad', label:'Antigüedad (años)', type:'number' },{ key:'acabados', label:'Acabados', options:['Premium','Alto','Medio','Básico'] },{ key:'acceso', label:'Acceso', options:['Pavimentado','Adoquinado','Mixto'] },{ key:'servicios', label:'Servicios', options:['Completo','Parcial'] },{ key:'uso', label:'Uso', options:['Residencial','Mixto','Renta'] },
]} />;
export const FincaForm = (p: Omit<Props, 'title'|'fields'>) => <Generic {...p} title='Ficha técnica rural · Finca' fields={[{key:'ciudad',label:'Ciudad'},{key:'zonaComunidad',label:'Zona/Comunidad'},{key:'extensionManzanas',label:'Extensión manzanas',type:'number'},{key:'topografia',label:'Topografía',options:['Plana','Ondulada','Quebrada']},{key:'acceso',label:'Acceso',options:['Todo tiempo','Estacional']},{key:'agua',label:'Agua',options:['Pozo','Río','Sistema']},{key:'energia',label:'Energía',options:['Sí','No']},{key:'tipoSuelo',label:'Tipo suelo',options:['Franco','Arcilloso','Arenoso']},{key:'usoPrincipal',label:'Uso principal',options:['Ganadera','Agrícola','Cafetalera','Forestal','Turística','Mixta']},{key:'cercaniaCarretera',label:'Cercanía carretera (km)',type:'number'},{key:'cercaniaCiudad',label:'Cercanía ciudad (km)',type:'number'},{key:'infraestructuraExistente',label:'Infraestructura',options:['Completa','Parcial','Mínima']}]}/>;
export const QuintaForm = (p: Omit<Props, 'title'|'fields'>) => <Generic {...p} title='Ficha técnica recreacional · Quinta' fields={[{key:'ciudad',label:'Ciudad'},{key:'zona',label:'Zona'},{key:'areaTotal',label:'Área total',type:'number'},{key:'construccion',label:'Construcción',type:'number'},{key:'piscina',label:'Piscina',options:['Sí','No']},{key:'jardines',label:'Jardines',options:['Amplios','Medios','Básicos']},{key:'rancho',label:'Rancho',options:['Sí','No']},{key:'acceso',label:'Acceso',options:['Excelente','Bueno','Regular']},{key:'topografia',label:'Topografía',options:['Plana','Semi plana','Inclinada']},{key:'servicios',label:'Servicios',options:['Completos','Parciales']},{key:'estadoGeneral',label:'Estado general',options:['Excelente','Bueno','Regular']}]}/>;
export const BodegaForm = (p: Omit<Props, 'title'|'fields'>) => <Generic {...p} title='Ficha técnica industrial · Bodega' fields={[{key:'ciudad',label:'Ciudad'},{key:'zona',label:'Zona'},{key:'areaConstruccion',label:'Área construcción',type:'number'},{key:'altura',label:'Altura (m)',type:'number'},{key:'accesoPesado',label:'Acceso pesado',options:['Sí','No']},{key:'andenCarga',label:'Andén carga',options:['Sí','No']},{key:'energiaTrifasica',label:'Energía trifásica',options:['Sí','No']},{key:'seguridad',label:'Seguridad',options:['24/7','Parcial','Básica']},{key:'oficinas',label:'Oficinas',options:['Sí','No']},{key:'estado',label:'Estado',options:['Excelente','Bueno','Regular']}]}/>;
export const ComercialForm = (p: Omit<Props, 'title'|'fields'>) => <Generic {...p} title='Ficha técnica comercial · Local' fields={[{key:'ciudad',label:'Ciudad'},{key:'zona',label:'Zona'},{key:'areaConstruccion',label:'Área construcción',type:'number'},{key:'parqueo',label:'Parqueo',options:['Amplio','Limitado','Sin parqueo']},{key:'flujoComercial',label:'Flujo comercial',options:['Alto','Medio','Bajo']},{key:'visibilidad',label:'Visibilidad',options:['Alta','Media','Baja']},{key:'acceso',label:'Acceso',options:['Excelente','Bueno','Regular']},{key:'tipoLocal',label:'Tipo local',options:['Plaza','A pie de calle','Centro comercial']},{key:'estado',label:'Estado',options:['Excelente','Bueno','Regular']},{key:'usoComercial',label:'Uso comercial',options:['Retail','Oficina','Servicios','Mixto']}]}/>;
