import { CIUDAD_UNICA, ZONAS_MATAGALPA } from '../constants/locations';
const topografias = ['Plano','Semi plano','Inclinado','Quebrado']; const accesos=['Pavimentado','Adoquinado','Macadán','Tierra']; const usos=['Residencial','Comercial','Mixto','Turístico']; const formas=['Regular','Irregular','Esquinero','Fondo amplio']; const niveles=['Alto','Medio','Bajo'];
export default function TerrenoForm({ value, onChange, onSubmit, loading }) { return <div className='grid gap-4 md:grid-cols-2 text-slate-200'>{field('Título del avalúo','titulo',value,onChange)}<selectField label='Ciudad' val={CIUDAD_UNICA} opts={[CIUDAD_UNICA]} onChange={()=>{}} disabled/><selectField label='Zona Matagalpa' val={value.zona||''} opts={ZONAS_MATAGALPA.map(z=>z.zona)} onChange={(v)=>onChange('zona',v)}/>{num('Área terreno m²','areaTerreno',value,onChange)}{selectField({label:'Topografía',val:value.topografia||'',opts:topografias,onChange:(v)=>onChange('topografia',v)})}{selectField({label:'Acceso',val:value.acceso||'',opts:accesos,onChange:(v)=>onChange('acceso',v)})}{selectField({label:'Uso potencial',val:value.usoPotencial||'',opts:usos,onChange:(v)=>onChange('usoPotencial',v)})}{selectField({label:'Forma terreno',val:value.formaTerreno||'',opts:formas,onChange:(v)=>onChange('formaTerreno',v)})}{selectField({label:'Nivel comercial',val:value.nivelComercial||'',opts:niveles,onChange:(v)=>onChange('nivelComercial',v)})}<checks title='Servicios' items={[['agua','Agua'],['energia','Energía'],['internet','Internet'],['drenaje','Drenaje'],['callePavimentada','Calle pavimentada']]} value={value.servicios||[]} onChange={(s)=>onChange('servicios',s)}/><tog label='Esquina' val={!!value.esquina} onChange={(v)=>onChange('esquina',v)}/><tog label='Cercanía principal' val={!!value.cercaniaPrincipal} onChange={(v)=>onChange('cercaniaPrincipal',v)}/><button onClick={onSubmit} disabled={loading} className='md:col-span-2 rounded-xl bg-amber-500 px-4 py-3 font-semibold text-slate-900'>Calcular avalúo técnico</button></div>; }
const base='rounded-xl border border-slate-700 bg-slate-900 p-3';
function field(label,key,v,onChange){return <label className={base}><span>{label}</span><input className='mt-2 w-full bg-slate-800 p-2 rounded' value={v[key]||''} onChange={e=>onChange(key,e.target.value)} /></label>}
function num(label,key,v,onChange){return <label className={base}><span>{label}</span><input type='number' className='mt-2 w-full bg-slate-800 p-2 rounded' value={v[key]||''} onChange={e=>onChange(key,Number(e.target.value))} /></label>}
function selectField({label,val,opts,onChange,disabled=false}){return <label className={base}><span>{label}</span><select disabled={disabled} className='mt-2 w-full bg-slate-800 p-2 rounded' value={val} onChange={e=>onChange(e.target.value)}><option value=''>Seleccionar</option>{opts.map(o=><option key={o} value={o}>{o}</option>)}</select></label>}
function checks({title,items,value,onChange}){return <div className={base}><p>{title}</p><div className='mt-2 grid grid-cols-2 gap-2'>{items.map(([k,l])=><label key={k}><input type='checkbox' checked={value.includes(k)} onChange={(e)=>onChange(e.target.checked?[...value,k]:value.filter((x)=>x!==k))}/> {l}</label>)}</div></div>}
function tog({label,val,onChange}){return <label className={base}><span>{label}</span><input type='checkbox' className='ml-3' checked={val} onChange={(e)=>onChange(e.target.checked)} /></label>}
