import { Award, BadgeDollarSign, BarChart3, Building2, Calendar, CheckCircle2, Home, MapPin, Phone, Ruler, ShieldCheck, UserRound } from 'lucide-react';
import { generateAvaluoAnalysis } from '../../utils/generateAvaluoAnalysis';

const money = (v: any) => new Intl.NumberFormat('es-NI', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(Number(v || 0));
const num = (v: any) => new Intl.NumberFormat('es-NI', { maximumFractionDigits: 2 }).format(Number(v || 0));
const date = (v: any) => { const d = v?.toDate ? v.toDate() : new Date(v || Date.now()); return d.toLocaleDateString('es-NI', { year: 'numeric', month: 'long', day: 'numeric' }); };
const labelize = (k: string) => k.replace(/([A-Z])/g, ' $1').replace(/_/g, ' ').replace(/^./, m => m.toUpperCase());
const clean = (v: any) => v !== undefined && v !== null && v !== '' && !(Array.isArray(v) && !v.length);
const text = (v: any): string => Array.isArray(v) ? v.join(', ') : typeof v === 'object' ? Object.entries(v).filter(([,x]) => clean(x)).map(([k,x]) => `${labelize(k)}: ${x ? 'Sí' : 'No'}`).join(' · ') : String(v);
const impact = (c: any) => { const n = Number(c || 1); const p = (n - 1) * 100; return `${p > 0 ? '+' : ''}${p.toFixed(1)}%`; };

function Img({ src, className }: { src?: string, className?: string }) {
  return src ? <img crossOrigin='anonymous' src={src} className={className} onError={(e) => { (e.currentTarget as HTMLImageElement).style.display = 'none'; }} /> : <div className={`${className} grid place-items-center bg-gradient-to-br from-slate-100 to-slate-200 text-slate-400`}>Imagen no disponible</div>;
}
function Page({ children, title }: any) { return <section className='avaluo-pdf-page relative mx-auto mb-6 h-[1123px] w-[794px] overflow-hidden bg-white p-12 text-slate-800 shadow-xl'><div className='absolute right-0 top-0 h-40 w-40 rounded-bl-full bg-amber-100/70' /><div className='relative z-10'>{title && <h2 className='mb-6 text-2xl font-bold text-[#0b1f3a]'>{title}</h2>}{children}</div><Footer /></section>; }
function Footer() { return <div className='absolute bottom-8 left-12 right-12 flex items-center justify-between border-t border-slate-200 pt-3 text-xs text-slate-500'><span>Norvin García · Real Estate</span><span>Informe técnico preliminar</span></div>; }
function Card({ icon: Icon = CheckCircle2, label, value }: any) { if (!clean(value)) return null; return <div className='rounded-2xl border border-slate-100 bg-slate-50 p-4'><Icon className='mb-2 h-5 w-5 text-amber-600' /><p className='text-xs uppercase tracking-wide text-slate-500'>{label}</p><p className='mt-1 font-semibold text-slate-800'>{value}</p></div>; }

export default function AvaluoPdfTemplate({ avaluo }: { avaluo: any }) {
  const agente = avaluo?.agenteEvaluador || 'Agente evaluador no especificado';
  const chars = Object.entries(avaluo?.caracteristicas || {}).filter(([k, v]) => !['zonaData', 'imagenPrincipalFile', 'imagenesAdicionalesFiles'].includes(k) && clean(v));
  const coefs = Array.isArray(avaluo?.coeficientesAplicados) ? avaluo.coeficientesAplicados : Object.entries(avaluo?.coeficientesAplicados || {}).map(([factor, coeficiente]) => ({ factor: labelize(factor), coeficiente, impacto: impact(coeficiente) }));
  const analisis = avaluo?.analisisProfesional || generateAvaluoAnalysis(avaluo);
  const galeria = (avaluo?.imagenesAdicionales || []).slice(0, 5);
  const factorGlobal = coefs.reduce((acc: number, c: any) => acc * Number(c.coeficiente || 1), 1);

  return <div className='avaluo-pdf-template bg-slate-200 p-6' style={{ fontFamily: 'Inter, ui-sans-serif, system-ui' }}>
    <Page><div className='flex items-center gap-3'><img src='/logo.png' className='h-14 w-14 rounded-full object-cover' /><div><p className='text-xs uppercase tracking-[.35em] text-amber-600'>Informe premium beta</p><h1 className='text-4xl font-black text-[#0b1f3a]'>Informe Técnico de Avalúo Inmobiliario</h1></div></div><div className='mt-10 rounded-[2rem] bg-[#0b1f3a] p-8 text-white'><p className='text-amber-300'>{avaluo?.tipoPropiedad || 'Propiedad'}</p><h2 className='mt-2 text-3xl font-bold'>{avaluo?.titulo || 'Avalúo inmobiliario'}</h2><p className='mt-3 flex gap-2 text-slate-200'><MapPin />{avaluo?.ciudad || 'Ciudad N/D'} · {avaluo?.zona || 'Zona N/D'}</p></div><Img src={avaluo?.imagenPrincipalUrl} className='mt-8 h-[420px] w-full rounded-[2rem] object-cover' /><div className='mt-8 grid grid-cols-2 gap-4'><Card icon={UserRound} label='Agente evaluador' value={agente}/><Card icon={Calendar} label='Fecha' value={date(avaluo?.createdAtServer || avaluo?.createdAt)}/></div></Page>
    <Page title='Datos generales'><div className='grid grid-cols-3 gap-4'><Card icon={Home} label='Tipo' value={avaluo?.tipoPropiedad}/><Card icon={MapPin} label='Ciudad' value={avaluo?.ciudad}/><Card icon={MapPin} label='Zona' value={avaluo?.zona}/><Card icon={Building2} label='Clasificación urbana' value={avaluo?.zonaSnapshot?.clasificacion}/><Card icon={ShieldCheck} label='Tipo de entorno' value={avaluo?.caracteristicas?.entorno || avaluo?.caracteristicas?.tipoEntorno}/><Card icon={Ruler} label='Área' value={num(avaluo?.areaM2Convertida || avaluo?.caracteristicas?.areaTerreno) + ' m²'}/><Card label='Unidad de área' value={avaluo?.unidadArea}/><Card icon={BadgeDollarSign} label='Valor por m²' value={money(avaluo?.valorM2)}/><Card icon={Award} label='Nivel de confianza' value={avaluo?.nivelConfianza}/><Card icon={BarChart3} label='Rango de mercado' value={`${money(avaluo?.rangoMercado?.minimo)} - ${money(avaluo?.rangoMercado?.maximo)}`}/></div>{!!galeria.length && <div className='mt-8'><h3 className='mb-3 text-lg font-bold text-[#0b1f3a]'>Galería de referencia</h3><div className='grid grid-cols-3 gap-3'>{galeria.map((src: string, i: number) => <Img key={src || i} src={src} className='h-36 rounded-2xl object-cover' />)}</div></div>}</Page>
    <Page title='Características evaluadas'><div className='grid grid-cols-2 gap-3'>{chars.map(([k, v]) => <Card key={k} label={labelize(k)} value={text(v)}/>)}</div></Page>
    <Page title='Análisis profesional'><div className='rounded-[2rem] border border-amber-200 bg-amber-50 p-8 text-xl leading-9 text-slate-700'>{analisis}</div></Page>
    <Page title='Resultado financiero'><div className='rounded-[2rem] bg-[#0b1f3a] p-10 text-white'><p className='text-sm uppercase tracking-[.25em] text-amber-300'>Valor final estimado</p><p className='mt-4 text-6xl font-black'>{money(avaluo?.valorFinal)}</p></div><div className='mt-6 grid grid-cols-2 gap-4'><Card label='Valor terreno' value={money(avaluo?.valorTerreno)}/><Card label='Valor construcción' value={money(avaluo?.valorConstruccion)}/><Card label='Rango mínimo' value={money(avaluo?.rangoMercado?.minimo)}/><Card label='Rango máximo' value={money(avaluo?.rangoMercado?.maximo)}/><Card label='Valor por m²' value={money(avaluo?.valorM2)}/><Card label='Factor global aplicado' value={factorGlobal.toFixed(3)}/><Card label='Nivel de confianza' value={avaluo?.nivelConfianza}/></div></Page>
    <Page title='Coeficientes y metodología'><div className='grid gap-3'>{coefs.map((c: any, i: number) => <div key={i} className='flex justify-between rounded-2xl bg-slate-50 p-4'><span className='font-semibold'>{c.factor || c.nombre}</span><span className='text-amber-700'>{c.impacto || impact(c.coeficiente)}</span></div>)}</div><p className='mt-8 leading-7 text-slate-600'>La metodología utiliza un modelo multicriterio que pondera ubicación, área, entorno, acceso, servicios, características físicas y coeficientes de mercado para construir una referencia técnica preliminar.</p><p className='mt-6 rounded-2xl bg-slate-100 p-5 text-sm text-slate-600'>Este informe corresponde a una estimación técnica preliminar generada mediante un modelo multicriterio de ponderación inmobiliaria. No sustituye un avalúo certificado emitido por perito valuador autorizado cuando la ley o una institución financiera lo requiera.</p></Page>
    <Page title='Cierre profesional'><div className='mt-20 text-center'><img src='/logo.png' className='mx-auto h-24 w-24 rounded-full object-cover' /><p className='mt-10 text-2xl font-bold text-[#0b1f3a]'>{agente}</p>{avaluo?.telefonoAgente && <p className='mt-2 flex justify-center gap-2 text-slate-600'><Phone />{avaluo.telefonoAgente}</p>}<p className='mt-2 text-slate-500'>Fecha de emisión: {date(new Date())}</p><div className='mx-auto mt-20 w-80 border-t border-slate-400 pt-3 text-sm text-slate-500'>Firma del agente evaluador</div><p className='mx-auto mt-16 max-w-xl leading-7 text-slate-600'>Gracias por confiar en Norvin García Real Estate. Este documento se entrega como soporte técnico y comercial para la toma de decisiones inmobiliarias.</p></div></Page>
  </div>;
}
