import { Award, BadgeDollarSign, Bath, BedDouble, Building2, CalendarDays, Camera, Car, CheckCircle2, ClipboardCheck, DoorOpen, Droplets, FileText, Hammer, Home, KeyRound, MapPin, ShieldCheck, Sofa, Sparkles, TrendingUp, Trees, Utensils, Waves, Wifi, Wind, Wrench } from 'lucide-react';
import { generateAvaluoAnalysis } from '../../utils/generateAvaluoAnalysis';
import '../../modules/avaluos/pdf/avaluoPdf.css';

const money = (v) => new Intl.NumberFormat('es-NI', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(Number(v || 0));
const num = (v) => new Intl.NumberFormat('es-NI', { maximumFractionDigits: 2 }).format(Number(v || 0));
const date = (v) => { const d = v?.toDate ? v.toDate() : new Date(v || Date.now()); return d.toLocaleDateString('es-NI', { year: 'numeric', month: 'long', day: 'numeric' }); };
const clean = (v) => v !== undefined && v !== null && v !== '' && !(Array.isArray(v) && !v.length);
const labelize = (k) => ({ areaBBQ:'BBQ', banos:'Baños', mediosBanos:'Medios baños', areaLavado:'Área lavado', cuartoServicio:'Cuarto servicio', salaFamiliar:'Sala familiar', cocinaModerna:'Cocina moderna', tipoCimentacion:'Cimentación', tipoParedes:'Paredes', tipoTecho:'Techo', tipoPiso:'Piso', tipoVentanas:'Ventanas', tipoPuertas:'Puertas', sistemaElectrico:'Sistema eléctrico', sistemaHidraulico:'Sistema hidráulico', sistemaSanitario:'Sanitario', sistemaPluvial:'Pluvial', accesoGeneral:'Accesos', tipoSuelo:'Tipo suelo', tipoEntorno:'Entorno', seguridadZona:'Seguridad', calidadConstructiva:'Calidad', estadoConstruccion:'Estado' }[k] || k.replace(/([A-Z])/g,' $1').replace(/^./,m=>m.toUpperCase()));
const text = (v) => Array.isArray(v) ? v.join(', ') : typeof v === 'object' ? Object.entries(v).filter(([,x])=>clean(x)).map(([k,x])=>`${labelize(k)}: ${x===true?'Sí':x}`).join(' · ') : String(v);
function Img({src, alt, wrapperClassName=''}){ const content=!src?<div className='avaluo-pdf-img-placeholder'>Imagen no disponible</div>:<img src={src} alt={alt} className='avaluo-pdf-img'/>; return <div className={wrapperClassName}>{content}</div>; }
function Page({children,title,cover=false}){return <section className={`avaluo-pdf-page house-pdf-page ${cover?'house-pdf-cover':''}`}><div className='avaluo-pdf-accent'/><div className='avaluo-pdf-content'>{title&&<><p className='house-pdf-kicker'>Informe residencial</p><h2 className='avaluo-pdf-title'>{title}</h2></>}{children}</div><Footer/></section>}
function Footer(){return <div className='avaluo-pdf-footer'><span>DIAMANTES REALTY GROUP</span><span>www.diamantesrealtygroup.com</span><span>Avalúo residencial</span></div>}
function Fact({icon:Icon=CheckCircle2,label,value}){ if(!clean(value))return null; return <div className='house-pdf-card'><Icon/><span>{label}</span><strong>{value}</strong></div> }
function Row({label,value}){ if(!clean(value))return null; return <div className='house-pdf-row'><span>{label}</span><strong>{text(value)}</strong></div> }
function Block({title,children}){return <div className='house-pdf-block'><h3>{title}</h3>{children}</div>}
function BoolIcon({k,v}){ if(!v)return null; const map={sala:Sofa,comedor:Utensils,cocina:Utensils,cocinaModerna:Sparkles,habitaciones:BedDouble,banos:Bath,mediosBanos:Bath,cuartoServicio:DoorOpen,areaLavado:Droplets,despensa:KeyRound,bodega:KeyRound,garaje:Car,patio:Trees,terraza:Trees,jardin:Trees,balcon:DoorOpen,oficina:FileText,salaFamiliar:Sofa,areaBBQ:Waves,piscina:Waves,rancho:Home}; const Icon=map[k]||CheckCircle2; return <div className='house-pdf-icon-item'><Icon/><span>{labelize(k)}</span><strong>{v===true?'Incluido':v}</strong></div> }
const scoreWord=(c)=> ['Excelente','Muy bueno','Bueno'].includes(c.estadoGeneral||c.estadoConstruccion)?'alto':['Regular','Malo'].includes(c.estadoGeneral||c.estadoConstruccion)?'moderado':'medio';
function technicalAnalysis(avaluo){ const c=avaluo.caracteristicas||{}; const base=generateAvaluoAnalysis(avaluo); return `${base}\n\nEl estado estructural se interpreta como ${c.estadoConstruccion||c.estadoGeneral||'referencial'}, con acabados ${c.calidadConstructiva||c.acabados||'acordes al segmento'} y una distribución ${c.salaFamiliar||c.oficina||c.terraza?'funcional y competitiva':'funcional para uso residencial tradicional'}. La ubicación en ${avaluo.zona||'la zona registrada'} incide en confort, seguridad y velocidad de comercialización; el nivel constructivo ${c.calidadConstructiva||'registrado'} y la presencia de extras como ${c.internetFibra?'internet de fibra, ':''}${c.aireAcondicionado?'aire acondicionado, ':''}${c.sistemaCCTV?'seguridad CCTV, ':''}mejoran la percepción de liquidez cuando están operativos. La competitividad comercial se considera de nivel ${scoreWord(c)}, sujeta a verificación documental, mantenimiento visible y comparación con ofertas activas del mismo sector.` }
export default function HouseReportPDF({avaluo}){
 const c=avaluo?.caracteristicas||{}, agente=avaluo?.agenteEvaluador||'Agente evaluador no especificado', galeria=(avaluo?.imagenesAdicionalesBase64||[]).filter(Boolean).slice(0,5), dist=['sala','comedor','cocina','cocinaModerna','habitaciones','banos','mediosBanos','cuartoServicio','areaLavado','despensa','bodega','garaje','patio','terraza','jardin','balcon','oficina','salaFamiliar','areaBBQ','piscina','rancho'];
 const rango=avaluo?.rangoMercado?`${money(avaluo.rangoMercado.minimo)} - ${money(avaluo.rangoMercado.maximo)}`:'';
 return <div className='avaluo-pdf-template house-pdf-template'>
  <Page cover><div className='house-cover-head'><img src='/logo.png'/><div><p>DIAMANTES REALTY GROUP</p><h1>INFORME TÉCNICO DE AVALÚO RESIDENCIAL</h1></div></div><Img src={avaluo?.imagenPrincipalBase64} alt='Fotografía principal' wrapperClassName='house-cover-photo'/><div className='house-cover-grid'><Fact icon={Home} label='Propiedad' value={avaluo?.titulo||'Avalúo residencial'}/><Fact icon={MapPin} label='Ciudad' value={avaluo?.ciudad}/><Fact icon={MapPin} label='Zona' value={avaluo?.zona}/><Fact icon={CalendarDays} label='Fecha' value={date(avaluo?.createdAtServer||avaluo?.createdAt)}/><Fact icon={Award} label='Agente' value={agente}/><Fact icon={FileText} label='N.º informe' value={avaluo?.id||'Pendiente'}/></div><div className='house-qr-space'>Espacio reservado para código QR futuro</div></Page>
  <Page title='Resumen ejecutivo'><div className='house-value-hero'><span>Valor estimado</span><strong>{money(avaluo?.valorFinal)}</strong><p>Rango comercial: {rango}</p></div><div className='house-grid-3'><Fact icon={Award} label='Nivel de confianza' value={avaluo?.nivelConfianza}/><Fact icon={Home} label='Tipo de vivienda' value={avaluo?.tipoPropiedad}/><Fact icon={Building2} label='Clasificación' value={avaluo?.zonaSnapshot?.clasificacion}/><Fact icon={ShieldCheck} label='Estado general' value={c.estadoGeneral||c.estadoConstruccion}/><Fact icon={Hammer} label='Nivel constructivo' value={c.calidadConstructiva||c.acabados}/><Fact icon={TrendingUp} label='Índice de comercialización' value={scoreWord(c)}/><Fact icon={CalendarDays} label='Vida útil estimada' value={c.antiguedad?`${c.antiguedad} años / revisar mantenimiento`:'Según inspección técnica'}/></div></Page>
  <Page title='Características del terreno'><Block title='Ficha territorial'><Row label='Área' value={`${num(avaluo?.areaM2Convertida||c.areaTerreno)} m²`}/><Row label='Frente' value={c.frenteTerreno}/><Row label='Fondo' value={c.fondoTerreno}/><Row label='Forma' value={c.formaTerreno}/><Row label='Topografía' value={c.topografia}/><Row label='Tipo suelo' value={c.tipoSuelo}/><Row label='Servicios' value={c.serviciosBasicos}/><Row label='Accesos' value={c.accesoGeneral}/><Row label='Entorno' value={c.tipoEntorno}/><Row label='Seguridad' value={c.seguridadZona}/></Block></Page>
  <Page title='Características de la construcción'><div className='house-grid-3'><Block title='General'><Row label='Área construcción' value={`${num(c.areaConstruccion)} m²`}/><Row label='Número de plantas' value={c.niveles}/><Row label='Antigüedad' value={c.antiguedad}/><Row label='Estado' value={c.estadoConstruccion}/><Row label='Calidad' value={c.calidadConstructiva}/></Block><Block title='Materiales'><Row label='Cimentación' value={c.tipoCimentacion}/><Row label='Paredes' value={c.tipoParedes}/><Row label='Techo' value={c.tipoTecho}/><Row label='Piso' value={c.tipoPiso}/><Row label='Ventanas' value={c.tipoVentanas}/><Row label='Puertas' value={c.tipoPuertas}/></Block><Block title='Instalaciones'><Row label='Sistema eléctrico' value={c.sistemaElectrico}/><Row label='Sistema hidráulico' value={c.sistemaHidraulico}/><Row label='Sanitario' value={c.sistemaSanitario}/><Row label='Pluvial' value={c.sistemaPluvial}/><Row label='Internet' value={c.internetFibra||c.serviciosBasicos?.internet}/><Row label='Aire acondicionado' value={c.aireAcondicionado}/></Block></div></Page>
  <Page title='Distribución'><div className='house-icon-grid'>{dist.map(k=><BoolIcon key={k} k={k} v={k==='habitaciones'||k==='banos'||k==='mediosBanos'?c[k]:c[k]}/>)}</div></Page>
  <Page title='Galería fotográfica'><Img src={avaluo?.imagenPrincipalBase64} alt='Fotografía principal' wrapperClassName='house-gallery-main'/><div className='house-gallery-grid'>{galeria.map((src,i)=><div key={src||i}><Img src={src} alt={`Fotografía ${i+1}`} wrapperClassName='house-gallery-cell'/><p>Fotografía adicional {i+1}</p></div>)}</div></Page>
  <Page title='Análisis técnico'><div className='avaluo-pdf-analysis'>{technicalAnalysis(avaluo).split(/\n\n/).map((p,i)=><p key={i}>{p}</p>)}</div></Page>
  <Page title='Conclusiones'><div className='house-grid-2'><Block title='Conclusión técnica'><p>La vivienda presenta un nivel constructivo {c.calidadConstructiva||'registrado'} y estado {c.estadoGeneral||c.estadoConstruccion||'a validar'}.</p></Block><Block title='Conclusión comercial'><p>El valor estimado se ubica en {money(avaluo?.valorFinal)}, con rango de negociación {rango||'según mercado'}.</p></Block><Block title='Fortalezas'><p>{[c.cocinaModerna&&'cocina moderna',c.garaje&&'garaje',c.seguridadZona&&`seguridad ${c.seguridadZona}`,c.tipoEntorno&&`entorno ${c.tipoEntorno}`].filter(Boolean).join(' · ')||'Ubicación, construcción y funcionalidad general.'}</p></Block><Block title='Aspectos a mejorar'><p>{['Regular','Malo'].includes(c.estadoGeneral||c.estadoConstruccion)?'Priorizar mantenimiento, acabados e instalaciones antes de comercializar.':'Mantener evidencias de mantenimiento, documentación y acabados.'}</p></Block><Block title='Recomendaciones'><p>Validar documentos, comparar con cierres recientes y preparar expediente fotográfico/técnico.</p></Block><Block title='Nivel de inversión y riesgos'><p>Inversión {scoreWord(c)}; riesgos principales: documentación, mantenimiento e inspección física final.</p></Block></div></Page>
  <Page><div className='avaluo-pdf-closing'><img src='/logo.png' className='logo-pdf logo-pdf--closing'/><h2>DIAMANTES REALTY GROUP</h2><div className='avaluo-pdf-closing-card'><Row label='Nombre' value={agente}/><Row label='Teléfono' value={avaluo?.telefonoAgente}/><Row label='Correo' value={avaluo?.correoAgente}/><Row label='Firma' value='____________________________'/></div><p>Este informe constituye una estimación técnica preliminar desarrollada mediante un modelo multicriterio de valoración inmobiliaria. No sustituye un avalúo pericial judicial ni una valoración bancaria certificada.</p><strong>www.diamantesrealtygroup.com</strong></div></Page>
 </div>
}
