import { Award, BadgeDollarSign, Bath, BedDouble, Building2, CalendarDays, Camera, Car, CheckCircle2, ClipboardCheck, DoorOpen, Droplets, FileText, Hammer, Home, KeyRound, MapPin, ShieldCheck, Sofa, Sparkles, TrendingUp, Trees, Utensils, Waves, Wifi, Wind, Wrench, Ruler, Factory, Percent, AlertTriangle, Target, BarChart3, Landmark, Lightbulb, ClipboardList, Gauge, Lock, Phone, Zap } from 'lucide-react';
import { generateAvaluoAnalysis } from '../../utils/generateAvaluoAnalysis';
import '../../modules/avaluos/pdf/avaluoPdf.css';

const money = (v) => new Intl.NumberFormat('es-NI', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(Number(v || 0));
const num = (v) => new Intl.NumberFormat('es-NI', { maximumFractionDigits: 2 }).format(Number(v || 0));
const date = (v) => { const d = v?.toDate ? v.toDate() : new Date(v || Date.now()); return d.toLocaleDateString('es-NI', { year: 'numeric', month: 'long', day: 'numeric' }); };
const clean = (v) => v !== undefined && v !== null && v !== '' && !(Array.isArray(v) && !v.length);
const yesNo = (v) => v === true ? 'Sí' : v === false ? 'No' : v;
const labelize = (k) => ({ areaBBQ:'BBQ', banos:'Baños', mediosBanos:'Medios baños', areaLavado:'Área lavado', cuartoServicio:'Cuarto servicio', salaFamiliar:'Sala familiar', cocinaModerna:'Cocina moderna', tipoCimentacion:'Cimentación', tipoParedes:'Paredes', tipoTecho:'Techo', tipoPiso:'Piso', tipoCieloRaso:'Cielo raso', tipoVentanas:'Ventanas', tipoPuertas:'Puertas', sistemaElectrico:'Sistema eléctrico', sistemaHidraulico:'Sistema hidráulico', sistemaSanitario:'Sanitario', sistemaPluvial:'Pluvial', accesoGeneral:'Accesos', tipoSuelo:'Tipo suelo', tipoEntorno:'Entorno', seguridadZona:'Seguridad', calidadConstructiva:'Calidad', estadoConstruccion:'Estado', internetFibra:'Internet fibra', portonElectrico:'Portón', sistemaCCTV:'Sistema de seguridad', cercaPerimetral:'Muro perimetral', nivelMantenimiento:'Mantenimiento', nivelComercial:'Nivel comercial' }[k] || k.replace(/([A-Z])/g,' $1').replace(/^./,m=>m.toUpperCase()));
const text = (v) => Array.isArray(v) ? v.map(yesNo).join(', ') : typeof v === 'object' ? Object.entries(v).filter(([,x])=>clean(x)).map(([k,x])=>`${labelize(k)}: ${yesNo(x)}`).join(' · ') : String(yesNo(v));
const impact = (coef = 1) => { const p = (Number(coef || 1) - 1) * 100; return `${p > 0 ? '+' : ''}${p.toFixed(1)}%`; };
const scoreWord=(c)=> ['Excelente','Muy bueno','Alta','Premium'].includes(c.estadoGeneral||c.estadoConstruccion||c.calidadConstructiva)?'alto':['Regular','Malo','Baja'].includes(c.estadoGeneral||c.estadoConstruccion||c.seguridadZona)?'moderado':'medio';
const riskWord=(c)=> ['Regular','Malo'].includes(c.estadoGeneral||c.estadoConstruccion) || ['Baja'].includes(c.seguridadZona) ? 'Medio' : 'Bajo';
const coefJustification = (factor, value, coef) => { const f=String(factor).toLowerCase(); const pct=(Number(coef||1)-1)*100; if(f.includes('seguridad')) return 'Influye en percepción de riesgo, demanda y velocidad de cierre.'; if(f.includes('acces')) return 'Define conectividad, facilidad de ingreso y atractivo operativo.'; if(f.includes('material')||f.includes('techo')||f.includes('piso')||f.includes('pared')) return 'Refleja durabilidad, costo de reposición y expectativa de mantenimiento.'; if(f.includes('edad')||f.includes('depreci')) return 'Ajusta vida útil remanente y obsolescencia física.'; if(f.includes('liquidez')||f.includes('demanda')) return 'Mide profundidad del mercado comprador en el segmento.'; if(Math.abs(pct)<0.1) return 'Condición neutral dentro del modelo técnico aplicado.'; return pct>0?'Condición favorable que incrementa la competitividad del inmueble.':'Ajuste conservador por condición inferior al estándar del mercado.'; };
function Img({src, alt, wrapperClassName=''}){ const content=!src?<div className='avaluo-pdf-img-placeholder'>Imagen no disponible</div>:<img src={src} alt={alt} className='avaluo-pdf-img'/>; return <div className={wrapperClassName}>{content}</div>; }
function Page({children,title,cover=false,page}){return <section className={`avaluo-pdf-page house-pdf-page ${cover?'house-pdf-cover':''}`}><div className='house-page-watermark'>DRG</div><div className='avaluo-pdf-accent'/><div className='avaluo-pdf-content'>{title&&<><p className='house-pdf-kicker'>Informe residencial</p><h2 className='avaluo-pdf-title'>{title}</h2></>}{children}</div><Footer page={page}/></section>}
function Footer({page}){return <div className='avaluo-pdf-footer house-pdf-footer'><img src='/logo.png'/><span>DIAMANTES REALTY GROUP</span><span>www.diamantesrealtygroup.com</span><span>{date(new Date())}</span><span>Pág. {page}</span><small>Documento generado automáticamente por el Sistema Profesional de Avalúos Inmobiliarios de DIAMANTES REALTY GROUP.</small></div>}
function Fact({icon:Icon=CheckCircle2,label,value}){ if(!clean(value))return null; return <div className='house-pdf-card'><Icon/><span>{label}</span><strong>{value}</strong></div> }
function Row({label,value}){ if(!clean(value))return null; return <div className='house-pdf-row'><span>{label}</span><strong>{text(value)}</strong></div> }
function Block({title,children,icon:Icon=ClipboardList}){return <div className='house-pdf-block'><h3><Icon/> {title}</h3>{children}</div>}
function Matrix({title, rows}){return <div className='house-matrix'><h3>{title}</h3><div className='house-matrix-head'><span>Factor</span><span>Valor seleccionado</span><span>Coeficiente</span><span>Justificación</span><span>Impacto</span></div>{rows.filter(r=>clean(r.value)).map((r,i)=><div className='house-matrix-row' key={title+i}><span>{r.factor}</span><strong>{text(r.value)}</strong><b>{Number(r.coef||1).toFixed(3)}</b><p>{r.justification||coefJustification(r.factor,r.value,r.coef)}</p><em>{r.impact||impact(r.coef)}</em></div>)}</div>}
const coefOf=(coefs,name,fallback=1)=> Number((coefs.find(x=>String(x.factor||'').toLowerCase().includes(name))||{}).coeficiente||fallback);
function makeMatrix(avaluo,c){ const coefs=Array.isArray(avaluo?.coeficientesAplicados)?avaluo.coeficientesAplicados:[]; const u=coefOf(coefs,'ubic',avaluo?.plusvaliaAplicada||1), t=coefOf(coefs,'terreno',1), cn=coefOf(coefs,'constru',1), e=coefOf(coefs,'estado',1), ex=coefOf(coefs,'extra',1), m=coefOf(coefs,'final',avaluo?.factorGlobal||1); return [
 {title:'UBICACIÓN',rows:[['Zona',avaluo?.zona,u],['Barrio',c.barrio||avaluo?.barrio,u],['Plusvalía',avaluo?.plusvaliaAplicada||avaluo?.zonaSnapshot?.factorPlusvalia,u],['Seguridad',c.seguridadZona,u],['Accesibilidad',c.accesoGeneral,u],['Desarrollo urbano',c.desarrolloUrbano,u],['Impacto individual','Ponderación sobre demanda, conectividad y posicionamiento',u]]},
 {title:'TERRENO',rows:[['Área',`${num(avaluo?.areaM2Convertida||c.areaTerreno)} m²`,t],['Forma',c.formaTerreno,t],['Topografía',c.topografia,t],['Frente',c.frenteTerreno,t],['Fondo',c.fondoTerreno,t],['Tipo suelo',c.tipoSuelo,t],['Servicios',c.serviciosBasicos,t],['Orientación',c.orientacion,t],['Impacto individual','Aprovechamiento físico y eficiencia del lote',t]]},
 {title:'CONSTRUCCIÓN',rows:[['Sistema estructural',c.tipoCimentacion||c.sistemaEstructural,cn],['Material paredes',c.tipoParedes,cn],['Material techo',c.tipoTecho,cn],['Material piso',c.tipoPiso,cn],['Calidad acabados',c.calidadConstructiva||c.acabados,cn],['Estado general',c.estadoGeneral||c.estadoConstruccion,e],['Edad',c.antiguedad,e],['Depreciación',avaluo?.depreciacion?money(avaluo.depreciacion):'Aplicada según edad y estado',e],['Mantenimiento',c.nivelMantenimiento||c.estadoConservacion,e],['Vida útil restante',c.vidaUtilRestante||'Estimación sujeta a inspección',e],['Impacto individual','Reposición, depreciación física y obsolescencia',cn]]},
 {title:'DISTRIBUCIÓN',rows:[['Cantidad habitaciones',c.habitaciones,m],['Cantidad baños',c.banos,m],['Garaje',c.garaje,m],['Terraza',c.terraza,m],['Patio',c.patio,m],['Iluminación',c.iluminacion||'Funcional',m],['Ventilación',c.ventilacion||'Funcional',m],['Circulación',c.circulacion||'Residencial',m],['Funcionalidad',c.funcionalidad||'Adecuada',m],['Impacto individual','Aceptación del usuario final y habitabilidad',m]]},
 {title:'AMENIDADES',rows:[['Jardín',c.jardin,ex],['Piscina',c.piscina,ex],['Seguridad',c.sistemaCCTV||c.alarma||c.seguridadZona,ex],['Bodega',c.bodega,ex],['Lavandería',c.areaLavado,ex],['Equipamiento',c.aireAcondicionado||c.internetFibra||c.sistemaInteligente,ex],['Impacto individual','Diferenciación frente a oferta comparable',ex]]},
 {title:'MERCADO',rows:[['Oferta disponible',avaluo?.ofertaDisponible||'Referencial sectorial',m],['Demanda',avaluo?.demanda||scoreWord(c),m],['Liquidez',avaluo?.indiceLiquidez||scoreWord(c),m],['Tiempo estimado de venta',avaluo?.tiempoVentaEstimado||'60 a 120 días según negociación',m],['Competencia',avaluo?.competencia||'Propiedades residenciales comparables',m],['Impacto individual','Absorción comercial, negociación y profundidad de demanda',m]]},
 ].map(g=>({...g,rows:g.rows.map(([factor,value,coef])=>({factor,value,coef}))})); }
function analysisSections(avaluo,c){ const base=generateAvaluoAnalysis(avaluo); return [ ['Análisis técnico', `${base} El modelo integra área de terreno, área construida, zona, servicios, accesos, calidad constructiva, estado de conservación y amenidades para obtener una referencia comercial trazable.`], ['Análisis constructivo', `La vivienda presenta sistema ${c.tipoCimentacion||'estructural registrado'}, paredes ${c.tipoParedes||'según inspección'}, techo ${c.tipoTecho||'reportado'} y piso ${c.tipoPiso||'reportado'}. La calidad ${c.calidadConstructiva||c.acabados||'declarada'} y el estado ${c.estadoGeneral||c.estadoConstruccion||'a validar'} determinan el valor de reposición y la depreciación técnica.`], ['Análisis comercial', `La ubicación en ${avaluo?.zona||'la zona registrada'} y ciudad ${avaluo?.ciudad||'registrada'} posiciona el activo con liquidez ${scoreWord(c)}. El rango de negociación depende de comparables activos, cierre documental y presentación del inmueble.`], ['Factores de riesgo', `Riesgo ${riskWord(c)}. Deben verificarse documentación, gravámenes, mantenimiento oculto, instalaciones eléctricas/hidrosanitarias y eventuales reparaciones previas a compraventa o financiamiento.`], ['Factores favorables', [c.garaje&&'garaje',c.terraza&&'terraza',c.jardin&&'jardín',c.piscina&&'piscina',c.internetFibra&&'internet de fibra',c.sistemaCCTV&&'seguridad'].filter(Boolean).join(', ') || 'Ubicación, funcionalidad residencial y condiciones físicas registradas.'], ['Conclusión técnica', `El valor comercial final recomendado es ${money(avaluo?.valorFinal)}, dentro de un rango de mercado razonable para la información suministrada y sujeto a inspección física final.`] ]; }
export default function HouseReportPDF({avaluo}){
 const c=avaluo?.caracteristicas||{}, agente=avaluo?.agenteEvaluador||'Agente evaluador no especificado', galeria=(avaluo?.imagenesAdicionalesBase64||[]).filter(Boolean).slice(0,5);
 const rango=avaluo?.rangoMercado?`${money(avaluo.rangoMercado.minimo)} - ${money(avaluo.rangoMercado.maximo)}`:'';
 const valorTerreno=avaluo?.valorTerreno, valorConstruccion=avaluo?.valorConstruccion, depreciacion=avaluo?.depreciacion||Math.max(0,(avaluo?.valorBase||0)-(valorTerreno||0)-(valorConstruccion||0));
 const matrix=makeMatrix(avaluo,c); const totalPages=10;
 return <div className='avaluo-pdf-template house-pdf-template'>
  <Page cover page={`1/${totalPages}`}><div className='house-cover-head'><img src='/logo.png'/><div><p>DIAMANTES REALTY GROUP</p><h1>INFORME TÉCNICO DE AVALÚO RESIDENCIAL</h1><h2>Informe técnico de valoración inmobiliaria.</h2></div></div><div className='house-cover-redline'/><Img src={avaluo?.imagenPrincipalBase64} alt='Fotografía principal' wrapperClassName='house-cover-photo'/><div className='house-cover-grid'><Fact icon={Home} label='Propiedad' value={avaluo?.titulo||'Avalúo residencial'}/><Fact icon={MapPin} label='Ciudad' value={avaluo?.ciudad}/><Fact icon={CalendarDays} label='Fecha' value={date(avaluo?.createdAtServer||avaluo?.createdAt)}/><Fact icon={Award} label='Agente' value={agente}/></div></Page>
  <Page title='Resumen ejecutivo' page={`2/${totalPages}`}><div className='house-value-hero'><span>Valor comercial final</span><strong>{money(avaluo?.valorFinal)}</strong><p>Rango comercial: {rango}</p></div><div className='house-grid-3'><Fact icon={BadgeDollarSign} label='Precio por m²' value={money(avaluo?.valorM2)}/><Fact icon={Trees} label='Precio del terreno' value={money(valorTerreno)}/><Fact icon={Building2} label='Precio de construcción' value={money(valorConstruccion)}/><Fact icon={Factory} label='Valor de reposición' value={money(avaluo?.valorBase)}/><Fact icon={Percent} label='Depreciación aplicada' value={money(depreciacion)}/><Fact icon={Landmark} label='Valor comercial final' value={money(avaluo?.valorFinal)}/><Fact icon={Target} label='Intervalo de confianza' value={avaluo?.nivelConfianza}/><Fact icon={Gauge} label='Índice de liquidez comercial' value={avaluo?.indiceLiquidez||scoreWord(c)}/><Fact icon={AlertTriangle} label='Nivel de riesgo' value={riskWord(c)}/></div></Page>
  <Page title='Ficha técnica residencial' page={`3/${totalPages}`}><div className='house-grid-2'><Block icon={Home} title='General'><Row label='Área terreno' value={`${num(avaluo?.areaM2Convertida||c.areaTerreno)} m²`}/><Row label='Área construcción' value={`${num(c.areaConstruccion)} m²`}/><Row label='Habitaciones' value={c.habitaciones}/><Row label='Baños' value={c.banos}/><Row label='Garaje' value={c.garaje}/><Row label='Plantas' value={c.niveles}/><Row label='Edad' value={c.antiguedad}/><Row label='Uso' value={c.usoInmueble||avaluo?.tipoPropiedad}/></Block><Block icon={Hammer} title='Construcción'><Row label='Sistema estructural' value={c.tipoCimentacion||c.sistemaEstructural}/><Row label='Material paredes' value={c.tipoParedes}/><Row label='Material techo' value={c.tipoTecho}/><Row label='Material piso' value={c.tipoPiso}/><Row label='Cielo raso' value={c.tipoCieloRaso}/><Row label='Estado conservación' value={c.estadoGeneral||c.estadoConstruccion}/><Row label='Acabados' value={c.acabados}/><Row label='Calidad constructiva' value={c.calidadConstructiva}/><Row label='Nivel constructivo' value={c.nivelConstructivo||c.calidadConstructiva}/></Block><Block icon={Zap} title='Instalaciones'><Row label='Agua' value={c.sistemaHidraulico||c.serviciosBasicos?.agua}/><Row label='Luz' value={c.sistemaElectrico||c.serviciosBasicos?.energia}/><Row label='Internet' value={c.internetFibra||c.serviciosBasicos?.internet}/><Row label='Telefonía' value={c.telefonia||c.serviciosBasicos?.telefonia}/><Row label='Drenaje' value={c.sistemaPluvial||c.serviciosBasicos?.drenaje}/></Block><Block icon={Sparkles} title='Extras'><Row label='Terraza' value={c.terraza}/><Row label='Patio' value={c.patio}/><Row label='Jardín' value={c.jardin}/><Row label='Piscina' value={c.piscina}/><Row label='Muro perimetral' value={c.cercaPerimetral||c.muroFrontal}/><Row label='Portón' value={c.portonElectrico}/><Row label='Sistema de seguridad' value={c.sistemaCCTV||c.alarma}/><Row label='Bodega' value={c.bodega}/><Row label='Lavandería' value={c.areaLavado}/></Block></div></Page>
  <Page title='Coeficientes aplicados I' page={`4/${totalPages}`}>{matrix.slice(0,3).map(g=><Matrix key={g.title} title={g.title} rows={g.rows}/>)}</Page>
  <Page title='Coeficientes aplicados II' page={`5/${totalPages}`}>{matrix.slice(3).map(g=><Matrix key={g.title} title={g.title} rows={g.rows}/>)}</Page>
  <Page title='Galería fotográfica' page={`6/${totalPages}`}><Img src={avaluo?.imagenPrincipalBase64} alt='Fotografía principal' wrapperClassName='house-gallery-main'/><div className='house-gallery-grid'>{galeria.map((src,i)=><div key={src||i}><Img src={src} alt={`Fotografía ${i+1}`} wrapperClassName='house-gallery-cell'/><p>Fotografía adicional {i+1}</p></div>)}</div></Page>
  <Page title='Análisis profesional' page={`7/${totalPages}`}><div className='house-analysis-grid'>{analysisSections(avaluo,c).map(([t,p])=><Block key={t} title={t}><p>{p}</p></Block>)}</div></Page>
  <Page title='Recomendaciones técnicas y comerciales' page={`8/${totalPages}`}><div className='house-grid-2'><Block icon={Lightbulb} title='Para comprador'><p>Solicitar inspección técnica, confirmar estado registral, validar instalaciones, revisar impuestos y contrastar el valor con comparables recientes antes de ofertar.</p></Block><Block icon={TrendingUp} title='Para vendedor'><p>Preparar expediente documental, fotografías profesionales, evidencia de mantenimiento y una estrategia de publicación alineada al rango comercial sugerido.</p></Block><Block icon={Wrench} title='Posibles mejoras'><p>{['Regular','Malo'].includes(c.estadoGeneral||c.estadoConstruccion)?'Priorizar pintura, humedad, instalaciones, acabados y reparaciones visibles.':'Mantener acabados, jardinería, limpieza profunda, iluminación y presentación escénica del inmueble.'}</p></Block><Block icon={BarChart3} title='Incrementos potenciales de valor'><p>Mejoras en seguridad, eficiencia energética, cocina, baños, paisajismo y mantenimiento preventivo pueden elevar la percepción de valor y reducir tiempo de venta.</p></Block><Block icon={ClipboardCheck} title='Observaciones técnicas'><p>El resultado es preliminar, depende de información suministrada y debe complementarse con levantamiento físico, medición, revisión documental y comparables cerrados.</p></Block></div></Page>
  <Page title='Resultado final' page={`9/${totalPages}`}><div className='house-result-hero'><strong>{money(avaluo?.valorFinal)}</strong><span>Valor final recomendado</span></div><div className='house-grid-3'><Fact icon={Trees} label='Valor terreno' value={money(valorTerreno)}/><Fact icon={Building2} label='Valor construcción' value={money(valorConstruccion)}/><Fact icon={Percent} label='Depreciación' value={money(depreciacion)}/><Fact icon={BadgeDollarSign} label='Valor ajustado' value={money((valorTerreno||0)+(valorConstruccion||0))}/><Fact icon={Gauge} label='Coeficiente total' value={Number(avaluo?.factorGlobal||1).toFixed(3)}/><Fact icon={Landmark} label='Valor final' value={money(avaluo?.valorFinal)}/><Fact icon={Target} label='Rango comercial' value={rango}/><Fact icon={TrendingUp} label='Precio sugerido publicación' value={money((avaluo?.rangoMercado?.maximo||avaluo?.valorFinal)*0.99)}/><Fact icon={AlertTriangle} label='Precio mínimo recomendable' value={money(avaluo?.rangoMercado?.minimo)}/><Fact icon={Award} label='Precio máximo recomendable' value={money(avaluo?.rangoMercado?.maximo)}/></div><div className='house-bar-chart'><i style={{width:'35%'}}/><i style={{width:'62%'}}/><i style={{width:'85%'}}/></div></Page>
  <Page title='Conclusiones y firma' page={`10/${totalPages}`}><div className='avaluo-pdf-closing'><img src='/logo.png' className='logo-pdf logo-pdf--closing'/><h2>DIAMANTES REALTY GROUP</h2><div className='avaluo-pdf-closing-card'><Row label='Nombre' value={agente}/><Row label='Teléfono' value={avaluo?.telefonoAgente}/><Row label='Correo' value={avaluo?.correoAgente}/><Row label='Firma' value='____________________________'/></div><p>Este informe constituye una estimación técnica preliminar desarrollada mediante un modelo multicriterio de valoración inmobiliaria. No sustituye un avalúo pericial judicial ni una valoración bancaria certificada.</p><strong>www.diamantesrealtygroup.com</strong></div></Page>
 </div>
}
